# Generated by Django 4.0.3 on 2022-03-24 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('post', models.ImageField(upload_to='')),
                ('text', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=250)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='User.usermodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='User.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=250)),
                ('comment_at', models.DateTimeField(auto_now_add=True)),
                ('comment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='User.usermodel')),
                ('comment_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_on', to='Post.postmodel')),
            ],
        ),
    ]
